---
title: "Statistical models"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Loading the libraries:
library(tidyverse)
library(tidyr)
library(dplyr)
library(stringr)
library(sp)
library(vegan)
library(lmerTest)
library(lme4)
library(broom)
```

```{r}
#Linear mixed effect models testing the effect of winter climate on population dynamics:
lmer_winter <- lmer(population_dynamic_measure ~ 
                          mean_winter_temperature +
                          winter_temperature_variability +
                          mean_winter_precipitation +
                          winter_precipitation_variability +
                          (1|AOU), data = df, na.action = "na.fail", REML=F)
r.squaredGLMM(lmer_winter)
summary(lmer_winter)
dredge(lmer_winter)
AIC(lmer_winter)
```

```{r}
#A loop that runs linear regression models for each species and aggregates the outputs to a table named 'winter_AOUs':

AOUlist <- unique(df$AOU) #creating the species AOU list

list_df <- vector(mode = "list", length = 20) 
index <- 0 #setting index to zero

for (i in AOUlist) {
  index <- index + 1
  AOU <- filter(df, AOU == i)
  AOU_lm_w <- lm(population_dynamic_measure ~
                          mean_winter_temperature +
                          winter_temperature_variability +
                          mean_winter_precipitation +
                          winter_precipitation_variability +
                 ,data=AOU)
  SUMtable <- tidy(summary(AOU_lm_w))
  AOU_lm_wconfint <- data.frame(confint(AOU_lm_w))
  AOU_lm_wconfint <- tibble::rownames_to_column(AOU_lm_wconfint, "term")
  merged <- merge(SUMtable, AOU_lm_wconfint, by = "term", all.x=TRUE)
  list_df[[index]] <- merged
  list_df[[index]] <- mutate(list_df[[index]], R_squared = summary(AOU_lm_w)$r.squared)
  list_df[[index]] <- mutate(list_df[[index]], adj_R_squared = summary(AOU_lm_w)$adj.r.squared)
  list_df[[index]] <- mutate(list_df[[index]], AOUname = i)
  list_df[[index]] <- mutate(list_df[[index]], Season = "Winter")
}

winter_AOUs <- bind_rows(list_df)
winter_AOUs$is_significant <- ifelse(winter_AOUs$p.value <= 0.01, winter_AOUs$p.value,"NotSignificant") #classifying p-values smaller than 0.01 as significant
winter_AOUs <- merge(x= winter_AOUs, y= countSubsetDB_30_1, by.x = "AOUname", by.y="x", all.x=TRUE)
winter_AOUs <- winter_AOUs %>% rename(NumberofTS = freq)
head(winter_AOUs)
```

